name: Build and deploy

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: Build and push
    runs-on: ubuntu-20.04

    steps:
      - name: ☁️ checkout repository
        uses: actions/checkout@v3

      - name: 🐳Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: 🔑 Login to registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.REGISTRY_URL }}:5000
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: 📦 Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ secrets.REGISTRY_URL }}:5000/pokebot:latest

  deploy:
    name: Deploy to server
    needs: [build]
    runs-on: ubuntu-20.04

    steps:
      - name: 🏗 SSH into cloud server and run bot
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            bash -c "docker stop pokebot || exit 0"
            bash -c "docker rm pokebot || exit 0"
            echo "${{ secrets.REGISTRY_PASSWORD }}" | \
              docker login ${{ secrets.REGISTRY_URL }}:5000 \
              --username ${{ secrets.REGISTRY_USERNAME }} \
              --password-stdin
            docker pull ${{ secrets.REGISTRY_URL }}:5000/pokebot:latest
            docker run -d \
              --name=pokebot \
              --restart=always \
              -e DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN }} \
              ${{ secrets.REGISTRY_URL }}:5000/pokebot:latest
